title: Chenghuizi Yang(杨程惠子)'s Homepage
page-top-title: Chenghuizi Yang
top-section-bg-text: Biology (Plant)
home-subtitle: Sen Li&ensp;|&ensp;杨程惠子
copyright-text: '&copy; Chenghuizi Yang 2024-2025. All Rights Reserved.'
